name: sole
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  animated_splash_screen: ^1.3.0
  fl_chart: ^0.66.0
  flutter_emoji: ^2.5.1

  #flavors
  flutter_flavorizr: ^2.2.1

  #networking
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  dio: ^5.3.3
  retrofit: ^4.0.3

  #models
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1

  #state management
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  riverpod_lint: ^2.1.0

  #routing
  auto_route: ^7.8.4

  #location services
  location: ^5.0.3
  geocoding: ^2.1.1
  rename_app: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  auto_route_generator: ^7.3.1
  riverpod_generator: ^2.3.2
  build_test: any
  build_web_compilers: any


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Bold.ttf
        - asset: assets/fonts/Lora-BoldItalic.ttf
        - asset: assets/fonts/Lora-Italic.ttf
        - asset: assets/fonts/Lora-Medium.ttf
        - asset: assets/fonts/Lora-MediumItalic.ttf
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-SemiBold.ttf
        - asset: assets/fonts/Lora-SemiBoldItalic.ttf

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit-Light.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-Thin.ttf

flavorizr:
  ide: "idea"
  flavors:
    dev:
      app:
        name: "WeatherApp-dev"

      android:
        applicationId: "com.example.sole.develop"

      ios:
        bundleId: "com.example.sole.develop"

    staging:
      app:
        name: "WeatherApp-staging"

      android:
        applicationId: "com.example.sole.staging"
      ios:
        bundleId: "com.example.sole.staging"

    production:
      app:
        name: "WeatherApp"

      android:
        applicationId: "com.example.sole"
      ios:
        bundleId: "com.example.sole"